#!/bin/bash

echo "==========================================="
echo ""
FILE=/Applications/Sileo.app/Sileo
if test -f "$FILE"; then
echo "[ ! ] Newer uicache version detected..."
echo "[ ! ] Refreshing icons..." & uicache --path /Applications/⠀.app/
else
echo "[ ! ] Refreshing icons..." & uicache
fi
echo ""
echo "Thanks for installing InvisibleWidget."
echo "Follow me on Twitter: @ginsudev."
echo ""
echo "==========================================="

exit 0
